---
title: "vMemEcc Behavior Analysis"
author: "Felix Klotzsche    ---    eioe"
date: "July 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Imports & loadings:
```{r, warning=F, message=F}
# Setup reticulate (need to run before loading mne):
library(reticulate)
use_condaenv(condaenv = "env_vMemEcc", required = TRUE)

library(tidyverse)
library(eegUtils)
library(stringr)
library(RColorBrewer)
library(ggsci)
library(mne)

mpl <- import("matplotlib")
mpl$use("tkAgg")
plt <- import("matplotlib.pyplot")

os <- import("os")
np <- import("numpy")

```



Data import:
```{r echo=FALSE, message=FALSE}

subjects       <- c('P06', 'P07', 'P08', 'P09')

# for development/debugging:
sub <- subjects[4]

data_path           <- 'D:/Felix/Seafile/Experiments/vMemEcc/Data/PilotData/'
data_raw_path       <- file.path(data_path, sub, 'EEG')
data_files          <- list.files(data_raw_path,
                                  pattern = '.vhdr', 
                                  full.names = TRUE)
raw_list <- list()

for (f in data_files) {
  raw_list <- append(raw_list, mne$io$read_raw_brainvision(f, preload = TRUE))
}

raw      <- mne$io$concatenate_raws(raw_list)
srate    <- raw$info['sfreq']
ev_list  <- mne$events_from_annotations(raw)
events   <- ev_list[[1]]
mode(events) <- 'integer'
event_id <- ev_list[[2]]

```

# preprocessing

```{r}
# band-pass filter at 0.01 - 40Hz:
filtered <- raw$filter(l_freq=0.01, h_freq=40)


# extract retention epochs and remove baseline 
# - (last 500ms of Cue interval):

# relevant events:
targ_evs <- list(range(150:173))
targ_evs <- 150:173
epoched = mne$Epochs(filtered, 
                     events, 
                     event_id = targ_evs, #as.integer(unlist(targ_evs)), 
                     tmin = -0.5, 
                     tmax=2.2, 
                     baseline=tuple(NULL, 0),
                     preload=TRUE)




# and remove baseline 
# - (last 200ms of Cue interval):



```
